env:
  browser: true
  commonjs: true
  node: true
  es6: true

settings:
  react:
    version: 'detect'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true

extends:
  - react-app
  - plugin:prettier/recommended
  - prettier/@typescript-eslint

rules:
  no-console: off
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
      allowTypedFunctionExpressions: true
